### ISSUE TITLE
Discourse post menu and p2pu topnav clashes

### ISSUE THREAD

**Issue by dirkcuys** [p2pu/p2pu-discourse-theme#1]
See [this issue](https://github.com/p2pu/learning-circles/issues/656). Also see here: https://meta.discourse.org/t/post-actions-disappears-for-some-reason/156356

```css
nav.collapsed {
    display: none !important;
}
```
Is used by the p2pu topnav for hamburger bar collapsing and also by discourse post actions.
